<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN_1" Id="{e1836af3-81b1-400d-b275-7e28fbb3edc4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_1
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
Camera();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN_1">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>