<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{05c9249a-2d2a-4719-9e1d-3233a5c387bc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
DomParser();
OperatorOverloading_Test();
DynamicArrays_Test();

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="6" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="2" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>